/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FoodSuggestion: typeof import('./src/components/FoodSuggestion.vue')['default']
    'LetsIcons:removeDuotone': typeof import('~icons/lets-icons/remove-duotone')['default']
    'LetsIcons:searchDuotone': typeof import('~icons/lets-icons/search-duotone')['default']
    'LetsIcons:signOutSqureLight': typeof import('~icons/lets-icons/sign-out-squre-light')['default']
    'LetsIcons:trashDuotone': typeof import('~icons/lets-icons/trash-duotone')['default']
    LetsIconsBack: typeof import('~icons/lets-icons/back')['default']
    'Logos:facebook': typeof import('~icons/logos/facebook')['default']
    'Logos:google': typeof import('~icons/logos/google')['default']
    Refrigerator: typeof import('./src/components/Refrigerator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
