@startuml Kokki

class Food {
  + name: String
  + ingredients: Ingredient[]
}

class Ingredient {
  + name: String
}

class Cooking {
  + name: String
  + description: String
  + chefIngredients: <Chef>Ingredient[]
  + food: Food

  + cook(): void
}

class Chef {
  + name: String
  + cooking: Cooking
  + ingredients: Ingredient[]

  + makeFood(): Cooking
}

Food "1" *--o "1..*" Ingredient
Chef "1" *-left-o "1..*" Ingredient
Chef "1" o-right-* "1" Cooking

Food "1" -left- "1" Cooking
Food "1" -up- "1" Chef

@enduml
