@startuml Kokki

entity DummyFoods {
  + name: String
  + ingredients: Ingredient[]
}

enum Ingredient {
  + name: String
  + amount: Number
  + unit: String
}

class Food {
  + name: String
  + foods: DummyFoods[]

  + getFoodInfo()
}

class Cooking {
  + chef: Chef

  + foodSuggestions(similarity: Float): Food[]
  + missingIngredients(food: Food): Ingredient[]
}

class Chef {
  + name: String
  + ingredients: Ingredient[]
  + favoriteFood: Food
}

Food "1" *--o "1..*" Ingredient
Chef "1" *-left-o "1..*" Ingredient
Chef "1" o-right-* "1" Cooking

Food "1" -left- "1" Cooking
Food "1" -up- "1" Chef
Food "1" -down- "1..*" DummyFoods

@enduml
