import { faker } from '@faker-js/faker';
import { IIngredient, IngredientEnum } from '../interfaces/Models';

export function createIngredient() {
  const uniqueNamesArray = mockIngredients.filter((obj, index, array) =>
    array.findIndex(item => item.name === obj.name) === index
  );

  return uniqueNamesArray;
}

const mockIngredients = [
  { name: 'Apple', type: 'FRUIT', unit: 'piece' },
  { name: 'Banana', type: 'FRUIT', unit: 'piece' },
  { name: 'Orange', type: 'FRUIT', unit: 'piece' },
  { name: 'Tomato', type: 'FRUIT', unit: 'piece' },
  { name: 'Carrot', type: 'VEGETABLE', unit: 'piece' },
  { name: 'Lettuce', type: 'VEGETABLE', unit: 'piece' },
  { name: 'Chicken', type: 'MEAT', unit: 'gram' },
  { name: 'Beef', type: 'MEAT', unit: 'gram' },
  { name: 'Salmon', type: 'FISH', unit: 'gram' },
  { name: 'Tuna', type: 'FISH', unit: 'gram' },
  { name: 'Milk', type: 'DAIRY', unit: 'milliliter' },
  { name: 'Cheese', type: 'DAIRY', unit: 'gram' },
  { name: 'Rice', type: 'GRAIN', unit: 'gram' },
  { name: 'Pasta', type: 'GRAIN', unit: 'gram' },
  { name: 'Almond', type: 'NUT', unit: 'gram' },
  { name: 'Walnut', type: 'NUT', unit: 'gram' },
  { name: 'Chia Seeds', type: 'SEED', unit: 'gram' },
  { name: 'Flaxseeds', type: 'SEED', unit: 'gram' },
  { name: 'Cumin', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Paprika', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Basil', type: 'HERB', unit: 'teaspoon' },
  { name: 'Oregano', type: 'HERB', unit: 'teaspoon' },
  { name: 'Olive Oil', type: 'OIL', unit: 'tablespoon' },
  { name: 'Coconut Oil', type: 'OIL', unit: 'tablespoon' },
  { name: 'Honey', type: 'SWEETENER', unit: 'tablespoon' },
  { name: 'Maple Syrup', type: 'SWEETENER', unit: 'tablespoon' },
  { name: 'Salt', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Pepper', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Water', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Coffee', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Wine', type: 'ALCOHOL', unit: 'milliliter' },
  { name: 'Beer', type: 'ALCOHOL', unit: 'milliliter' },
  { name: 'Eggs', type: 'OTHER', unit: 'piece' },
  { name: 'Butter', type: 'OTHER', unit: 'gram' },
  { name: 'Onion', type: 'OTHER', unit: 'piece' },
  { name: 'Garlic', type: 'OTHER', unit: 'piece' },
  { name: 'Ginger', type: 'OTHER', unit: 'gram' },
  { name: 'Lemon', type: 'OTHER', unit: 'piece' },
  { name: 'Cucumber', type: 'OTHER', unit: 'piece' },
  { name: 'Spinach', type: 'OTHER', unit: 'gram' },
  { name: 'Broccoli', type: 'OTHER', unit: 'gram' },
  { name: 'Cabbage', type: 'OTHER', unit: 'piece' },
  { name: 'Potato', type: 'OTHER', unit: 'piece' },
  { name: 'Zucchini', type: 'OTHER', unit: 'piece' },
  { name: 'Quinoa', type: 'OTHER', unit: 'gram' },
  { name: 'Lentils', type: 'OTHER', unit: 'gram' },
  { name: 'Chickpeas', type: 'OTHER', unit: 'gram' },
  { name: 'Sesame Seeds', type: 'OTHER', unit: 'gram' },
  { name: 'Vanilla Extract', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Cinnamon', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Soy Sauce', type: 'OTHER', unit: 'tablespoon' },
  { name: 'Vinegar', type: 'OTHER', unit: 'tablespoon' },
  { name: 'Cocoa Powder', type: 'OTHER', unit: 'tablespoon' },
  { name: 'Sugar', type: 'OTHER', unit: 'gram' },
  { name: 'Salted Butter', type: 'OTHER', unit: 'gram' },
  { name: 'Red Wine', type: 'OTHER', unit: 'milliliter' },
  { name: 'White Wine', type: 'OTHER', unit: 'milliliter' },
  { name: 'Grapes', type: 'OTHER', unit: 'piece' },
  { name: 'Strawberries', type: 'OTHER', unit: 'piece' },
  { name: 'Blueberries', type: 'OTHER', unit: 'gram' },
  { name: 'Avocado', type: 'OTHER', unit: 'piece' },
  { name: 'Pineapple', type: 'OTHER', unit: 'piece' },
  { name: 'Mango', type: 'OTHER', unit: 'piece' },
  { name: 'Peanut Butter', type: 'OTHER', unit: 'tablespoon' },
  { name: 'Almond Butter', type: 'OTHER', unit: 'tablespoon' },
  { name: 'Chocolate', type: 'OTHER', unit: 'gram' },
  { name: 'Mint', type: 'OTHER', unit: 'gram' },
  { name: 'Coconut Milk', type: 'OTHER', unit: 'milliliter' },
  { name: 'Cashews', type: 'OTHER', unit: 'gram' },
  { name: 'Hazelnuts', type: 'OTHER', unit: 'gram' },
  { name: 'Bread', type: 'OTHER', unit: 'slice' },
  { name: 'Yogurt', type: 'OTHER', unit: 'gram' },
  { name: 'Cilantro', type: 'OTHER', unit: 'gram' },
  { name: 'Mushrooms', type: 'OTHER', unit: 'gram' },
  { name: 'Parsley', type: 'OTHER', unit: 'gram' },
  { name: 'Thyme', type: 'OTHER', unit: 'gram' },
  { name: 'Rosemary', type: 'OTHER', unit: 'gram' },
  { name: 'Lime', type: 'OTHER', unit: 'piece' },
  { name: 'Celery', type: 'OTHER', unit: 'piece' },
  { name: 'Peas', type: 'OTHER', unit: 'gram' },
  { name: 'Asparagus', type: 'OTHER', unit: 'piece' },
  { name: 'Cauliflower', type: 'OTHER', unit: 'piece' },
  { name: 'Parsnip', type: 'VEGETABLE', unit: 'piece' },
  { name: 'Artichoke', type: 'VEGETABLE', unit: 'piece' },
  { name: 'Leek', type: 'VEGETABLE', unit: 'piece' },
  { name: 'Beetroot', type: 'VEGETABLE', unit: 'piece' },
  { name: 'Radish', type: 'VEGETABLE', unit: 'piece' },
  { name: 'Brussels Sprouts', type: 'VEGETABLE', unit: 'piece' },
  { name: 'Cauliflower Rice', type: 'VEGETABLE', unit: 'gram' },
  { name: 'Chia Seeds', type: 'GRAIN', unit: 'gram' },
  { name: 'Flax Seeds', type: 'GRAIN', unit: 'gram' },
  { name: 'Sorghum', type: 'GRAIN', unit: 'gram' },
  { name: 'Bulgur', type: 'GRAIN', unit: 'gram' },
  { name: 'Millet', type: 'GRAIN', unit: 'gram' },
  { name: 'Rye', type: 'GRAIN', unit: 'gram' },
  { name: 'Pumpkin Seeds', type: 'SEED', unit: 'gram' },
  { name: 'Sunflower Seeds', type: 'SEED', unit: 'gram' },
  { name: 'Poppy Seeds', type: 'SEED', unit: 'gram' },
  { name: 'Mustard Seeds', type: 'SEED', unit: 'gram' },
  { name: 'Cardamom', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Nutmeg', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Paprika', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Turmeric', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Bay Leaf', type: 'HERB', unit: 'piece' },
  { name: 'Oregano', type: 'HERB', unit: 'gram' },
  { name: 'Sage', type: 'HERB', unit: 'gram' },
  { name: 'Basil', type: 'HERB', unit: 'gram' },
  { name: 'Coconut Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Olive Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Canola Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Flour', type: 'OTHER', unit: 'gram' },
  { name: 'Cornstarch', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Maple Syrup', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Honey', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Ketchup', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Mayonnaise', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Soy Sauce', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Worcestershire Sauce', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Orange Juice', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Apple Juice', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Coconut Water', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Almond Milk', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Red Wine', type: 'ALCOHOL', unit: 'milliliter' },
  { name: 'White Wine', type: 'ALCOHOL', unit: 'milliliter' },
  { name: 'Vodka', type: 'ALCOHOL', unit: 'milliliter' },
  { name: 'Rum', type: 'ALCOHOL', unit: 'milliliter' },
  { name: 'Sugar', type: 'OTHER', unit: 'gram' },
  { name: 'Salt', type: 'OTHER', unit: 'gram' },
  { name: 'Black Pepper', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Soy Milk', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Cashew Milk', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Hazelnut Milk', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Rice Milk', type: 'BEVERAGE', unit: 'milliliter' },
  { name: 'Coconut Cream', type: 'DAIRY', unit: 'milliliter' },
  { name: 'Whipping Cream', type: 'DAIRY', unit: 'milliliter' },
  { name: 'Greek Yogurt', type: 'DAIRY', unit: 'gram' },
  { name: 'Sour Cream', type: 'DAIRY', unit: 'gram' },
  { name: 'Gruyere Cheese', type: 'DAIRY', unit: 'gram' },
  { name: 'Blue Cheese', type: 'DAIRY', unit: 'gram' },
  { name: 'Parmesan Cheese', type: 'DAIRY', unit: 'gram' },
  { name: 'Mozzarella Cheese', type: 'DAIRY', unit: 'gram' },
  { name: 'Mackerel', type: 'FISH', unit: 'gram' },
  { name: 'Tuna', type: 'FISH', unit: 'gram' },
  { name: 'Cod', type: 'FISH', unit: 'gram' },
  { name: 'Salmon', type: 'FISH', unit: 'gram' },
  { name: 'Lamb', type: 'MEAT', unit: 'gram' },
  { name: 'Pork', type: 'MEAT', unit: 'gram' },
  { name: 'Beef', type: 'MEAT', unit: 'gram' },
  { name: 'Chicken', type: 'MEAT', unit: 'gram' },
  { name: 'Rice', type: 'GRAIN', unit: 'gram' },
  { name: 'Quinoa', type: 'GRAIN', unit: 'gram' },
  { name: 'Barley', type: 'GRAIN', unit: 'gram' },
  { name: 'Couscous', type: 'GRAIN', unit: 'gram' },
  { name: 'Almond Flour', type: 'GRAIN', unit: 'gram' },
  { name: 'Oat Flour', type: 'GRAIN', unit: 'gram' },
  { name: 'Coconut Flour', type: 'GRAIN', unit: 'gram' },
  { name: 'Whole Wheat Flour', type: 'GRAIN', unit: 'gram' },
  { name: 'Walnuts', type: 'NUT', unit: 'gram' },
  { name: 'Pecans', type: 'NUT', unit: 'gram' },
  { name: 'Hazelnuts', type: 'NUT', unit: 'gram' },
  { name: 'Pistachios', type: 'NUT', unit: 'gram' },
  { name: 'Vanilla Extract', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Cinnamon', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Cumin', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Paprika', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Dried Basil', type: 'HERB', unit: 'teaspoon' },
  { name: 'Dried Oregano', type: 'HERB', unit: 'teaspoon' },
  { name: 'Dried Thyme', type: 'HERB', unit: 'teaspoon' },
  { name: 'Dried Rosemary', type: 'HERB', unit: 'teaspoon' },
  { name: 'Sesame Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Olive Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Coconut Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Canola Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Maple Syrup', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Honey', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Agave Nectar', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Molasses', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Ketchup', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Mustard', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Basil Leaves', type: 'HERB', unit: 'teaspoon' },
  { name: 'Dill', type: 'HERB', unit: 'teaspoon' },
  { name: 'Mint Leaves', type: 'HERB', unit: 'teaspoon' },
  { name: 'Parsley', type: 'HERB', unit: 'teaspoon' },
  { name: 'Chili Powder', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Turmeric', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Ginger Powder', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Coriander', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Sunflower Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Avocado Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Peanut Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Truffle Oil', type: 'OIL', unit: 'teaspoon' },
  { name: 'Stevia', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Monk Fruit Sweetener', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Coconut Sugar', type: 'SWEETENER', unit: 'teaspoon' },
  { name: 'Black Pepper', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Sea Salt', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Balsamic Vinegar', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'White Wine Vinegar', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Red Wine Vinegar', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Soy Sauce', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Fish Sauce', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Worcestershire Sauce', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Peanut Butter', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Almond Butter', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Tahini', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Nutritional Yeast', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Chia Seeds', type: 'SEED', unit: 'teaspoon' },
  { name: 'Flax Seeds', type: 'SEED', unit: 'teaspoon' },
  { name: 'Hemp Seeds', type: 'SEED', unit: 'teaspoon' },
  { name: 'Pumpkin Seeds', type: 'SEED', unit: 'teaspoon' },
  { name: 'Poppy Seeds', type: 'SEED', unit: 'teaspoon' },
  { name: 'Cumin Seeds', type: 'SEED', unit: 'teaspoon' },
  { name: 'Mustard Seeds', type: 'SEED', unit: 'teaspoon' },
  { name: 'Sesame Seeds', type: 'SEED', unit: 'teaspoon' },
  { name: 'Cardamom Pods', type: 'SPICE', unit: 'teaspoon' },
  { name: 'Vanilla Extract', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Lemon Juice', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Lime Juice', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Orange Juice', type: 'OTHER', unit: 'teaspoon' },
  { name: 'Apple Cider Vinegar', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Rice Vinegar', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Hoisin Sauce', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Sriracha', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Mayonnaise', type: 'CONDIMENT', unit: 'teaspoon' },
  { name: 'Greek Yogurt', type: 'DAIRY', unit: 'teaspoon' },
  { name: 'Sour Cream', type: 'DAIRY', unit: 'teaspoon' },
  { name: 'Coconut Milk', type: 'DAIRY', unit: 'teaspoon' },
  { name: 'Cashews', type: 'NUT', unit: 'teaspoon' },
  { name: 'Almonds', type: 'NUT', unit: 'teaspoon' },
  { name: 'Walnuts', type: 'NUT', unit: 'teaspoon' },
  { name: 'Pecans', type: 'NUT', unit: 'teaspoon' },
  { name: 'Hazelnuts', type: 'NUT', unit: 'teaspoon' },
  { name: 'Brazil Nuts', type: 'NUT', unit: 'teaspoon' },
  { name: 'Macadamia Nuts', type: 'NUT', unit: 'teaspoon' },
]
